name: Deploy Website to Debian 10 VM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Node.js and npm (if needed)
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Use the appropriate Node.js version for your project

    - name: Install SSHpass
      run: sudo apt-get install -y sshpass

    - name: Deploy Website
      run: |
        sshpass -p "${{ secrets.VM_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }} -p ${{ secrets.SSH_PORT }} '
          cd /home/tiagomartinssousa/MatchUp-Web-App/matchup-web &&
          git pull origin main &&
          npm install &&
          npm run build &&
          sudo systemctl restart nginx'
          
